/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as LabLiquidGlassRouteImport } from './routes/lab/liquid-glass'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125ProjectsRouteImport } from './routes/{-$locale}/projects'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const LabLiquidGlassRoute = LabLiquidGlassRouteImport.update({
  id: '/lab/liquid-glass',
  path: '/lab/liquid-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProjectsRoute =
  Char123LocaleChar125ProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lab/liquid-glass': typeof LabLiquidGlassRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lab/liquid-glass': typeof LabLiquidGlassRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lab/liquid-glass': typeof LabLiquidGlassRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/lab/liquid-glass'
    | '/{-$locale}/projects'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/lab/liquid-glass'
    | '/{-$locale}/projects'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/lab/liquid-glass'
    | '/{-$locale}/projects'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LabLiquidGlassRoute: typeof LabLiquidGlassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/liquid-glass': {
      id: '/lab/liquid-glass'
      path: '/lab/liquid-glass'
      fullPath: '/lab/liquid-glass'
      preLoaderRoute: typeof LabLiquidGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/projects': {
      id: '/{-$locale}/projects'
      path: '/projects'
      fullPath: '/{-$locale}/projects'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125ProjectsRoute: typeof Char123LocaleChar125ProjectsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125ProjectsRoute: Char123LocaleChar125ProjectsRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LabLiquidGlassRoute: LabLiquidGlassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
